spring.application.name=RestDemo

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#postgresql

spring.datasource.url=jdbc:postgresql://localhost:5432/restdb
spring.datasource.username=postgres
spring.datasource.password=password

#jpa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true